Repository bedita/web-tools, pull requests merged in 2022-10, with the labels that each got.

#77 Show JSON error response on `application/json` Accept
  src/Error/ExceptionRenderer.php
  tests/TestCase/Error/ExceptionRendererTest.php
Labels: enhancement, release:minor

#81 Use same `roles` format in `Identifier` response
  src/Identifier/ApiIdentifier.php
  src/Identifier/OAuth2Identifier.php
  tests/TestCase/Identifier/OAuth2IdentifierTest.php
Labels: bug

#78 Add deprecations check
  composer.json
  src/Command/CacheClearallCommand.php
  tests/TestCase/View/Helper/AssetHelperTest.php
  tests/TestCase/View/Helper/ThumbHelperTest.php
Labels: enhancement

#82 Fix replace translations when translated_fields not found
  src/Controller/Component/ApiFormatterComponent.php
  tests/TestCase/Controller/Component/ApiFormatterComponentTest.php
Labels: bug, release:patch
