Repository bedita/web-tools, pull requests merged in 2025-02, with the labels that each got.

#101 Api response clean utility
  src/Controller/Component/ApiFormatterComponent.php
  src/Utility/ApiTools.php
  tests/TestCase/Controller/Component/ApiFormatterComponentTest.php
  tests/TestCase/Utility/ApiToolsTest.php
Labels: release:minor, feature

#102 API formatter clean attributes
  src/Controller/Component/ApiFormatterComponent.php
  src/Utility/ApiTools.php
  tests/TestCase/Controller/Component/ApiFormatterComponentTest.php
  tests/TestCase/Utility/ApiToolsTest.php
Labels: enhancement, release:patch

#103 Always cast `provider_username` to string
  src/Authenticator/OAuth2Authenticator.php
Labels: bug, release:patch
